version: "3"

services:
  frontend:
    image: front
    container_name: front
    build: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/usr/src/app
      - /usr/src/app/node_modules
      - media:/media
      - certs:/etc/ssl/certs
    environment:
      - NODE_ENV=development
    networks:
      - transcendence
    depends_on:
      - backend

  backend:
    image: back
    container_name: back
    build:
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
      - ./back-end:/app
      - media:/media
      - certs:/etc/ssl/certs
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - transcendence
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    env_file: .env
    networks:
      - transcendence
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
  media:
  certs:

networks:
  transcendence:
    name: transcendence